models_cloudbreak/gateway_json.go
Side note: In order to avoid confusion the signCert and signPublic key has been removed as well.
=> DPAAS-81 add token topology cert and remove unused signCert and signPK

dataplane/cmd/tenant.go, dataplane/cmd/user.go, dataplane/flags/flags.go, dataplane/tenant/tenant.go, dataplane/user/user.go
Allow to select users from strategy local. This is required since their can be 2 strategies active at same time.
Removed disable tenant command. Will be added later when we have enable logic build
=> BUG-116180: strategy selection while assigning roles

cmd/command_tree.go, dataplane/flags/flags.go
There is no new-year without coding. Refine `command-tree` to be pstree like:
```
dp
├── audit
│   ├── list
│   │   ├── blueprint
│   │   ├── cluster
│   │   ├── credential
│   │   ├── database
│   │   ├── imagecatalog
│   │   ├── ldap
│   │   └── recipe
│   └── describe
├── blueprint
│   ├── create
│   │   ├── from-url
│   │   └── from-file
│   ├── delete
│   ├── describe
│   └── list
├── cloud
│   ├── availability-zones
│   ├── instances
│   ├── regions
│   └── volumes
│       ├── aws
│       ├── azure
│       └── gcp
├── cluster
│   ├── change-ambari-password
│   ├── change-image
│   ├── create
│   ├── delete
│   ├── describe
│   ├── generate-template
│   │   ├── yarn
│   │   ├── aws
│   │   │   ├── new-network
│   │   │   ├── existing-network
│   │   │   └── existing-subnet
│   │ …
```
=> pstree like command structure

tests/Makefile
The Jenkins checks out code to be built by commit. The previous script returned "HEAD" in this case, which resulted in the urls pointing to master, where the blueprint folder was renamed.
=> CB-603 Determine active branch for checkouted commit

Makefile, cloudbreak/credential/credential.go, cloudbreak/stack/stack.go, cloudbreak/stack/stack_functions_test.go
occasionally builds fail due to various dependencies so it's a good time to upgrade and use the saved vendor folder instead
=> update rc-2.9 to built on go 1.12 with vendoring enabled

dataplane/clusterdefinition/clusterdefinition.go
The CDH cluster definition does not have a corresponding Blueprint field
in its JSON, so instead the CLI will print "undefined" in these
instances.
=> CB-597. Fix error when reading CDH cluster definitions.

dataplane/clusterdefinition/clusterdefinition.go
This allows the CLI  to properly display information from CDH blueprints.
=> CB-597. Parse out CDH version from CDH blueprints.

tests/spec/e2e/cluster.rb
CB-1050 disable downscale test due to ambari problem on openstack
=> CB-1050 disable downscale test due to ambari problem on openstack

completion/zsh_autocomplete, dataplane/cmd/cluster.go, dataplane/config/config.go, dataplane/flags/flags.go, tests/scripts/test_run.sh
Replace some leftover `cb` references, eg.:
```
$ dp database create mysql
...
--not-validated            [DEPRECATED] has no effect, use 'cb database test ...' command instead
```
Built locally and verified the output of the same commands, eg.:
```
$ build/$(uname)/dp database create mysql
...
--not-validated            [DEPRECATED] has no effect, use 'dp database test ...' command instead
```
=> [CB-1281] dp cli reports itself as cb in error messages

dataplane/cmd/recipe.go, dataplane/flags/flags.go
*  Make description of `--file` more generic, as it currently references "blueprint" even for recipes.
* Recipe can only be created from file, not URL.
=> Generic description for --file

dataplane/stack/stack.go
The following error occurs when creating CM cluster and passing admin username/password as command-line parameters:
```
$ dp cluster create --cli-input-json def.json --name cluster1 --input-json-param-user admin --input-json-param-password *****
ERROR: Missing clusterRequest.ambariRequest node in JSON
```
Since the username/password are at the cluster-level, the check for Ambari node seems unnecessary.
=> Fix "Missing clusterRequest.ambariRequest node" error

dataplane/env/environment.go
There appears to be some leftover debug in `env describe` output, so it's not valid JSON:
```
$ dp env describe --name ganeshk-omg
&{CloudPlatform:AWS Creator:crn:altus:iam:us-west-1:...
map[us-west-2:US West (Oregon)]
{
"Name": "ganeshk-omg",
"CloudPlatform": "AWS",
"Status": "CORRUPTED",
...
}
```
```
$ ./build/Darwin/dp env describe --name ganeshk-omg
{
"Name": "ganeshk-omg",
"CloudPlatform": "AWS",
"Status": "CORRUPTED",
...
}
```
=> CB-1317. Remove leftover debug

dataplane/env/environment.go
The new response (excerpt):
`dp env describe --name gtopolyai-ycloud-env1`
`{
"Name": "gtopolyai-ycloud-env1",
"Authentication": {
"loginUserName": "cloudbreak",
"publicKey": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCl9n1RqkCVZlgtNyxG6wwY7WIgXPq+YyRf/i7y0hpvVo+KLcQEfUe6vK34ZKMp9nmsBhsaSAaJSL3jWYSKlyAt2iEyNuORaNXQS5yiHGHtvCOTKQCB1X2UTqAoE+DI8U00IMApDzibcJU32qX4d5DkCq70A4/nec3KVJnfST5FTzRsN+hf0X/1e59PIdq280IqVU2Nw5BdNUOMcsHYug59i1EkccGbHyBwwtzur+eKF9OsRS7L0fSc9hka266mQZnIE3YH8KFuN9SySaR9x8YGeWSr1D3s4HV2/6pN4vBWJ1huF6q/Y3F4PvlmtHcFY3fzzHuE9J6BVhpvhZn6jJ98CC7sTrWI4VUB/wLiwGMnlstMeBkyDSJ1V9keX8DGXhMy7JRKQz6OBjLRSDBd4es3PFNyk8LCc7sQsm84U340CXVHgxLWge0J8xsmT/b8xrdq8L8p8hsZ4IlIPi+UCQLYSGcNtpp3G06+26gxCqbBvBFiEEq9pNzRjp2RezVp/UE0bq/SU8GjdggqTW6GH0yF/1VervNcV9vRaiQLkU4m5XyJTXt9THAli//RbqggHyDTFqngKZJi …
=> CB-2902 Environment response should contain ssh-keypair name

Makefile, dataplane/cmd/redbeams.go, dataplane/oauth/oauth_client.go, dataplane/redbeams/redbeams.go
The following new redbeams dbserver commands are implemented in the CLI:
- describe
- describe-by-name
- get-status
- get-status-by-name
- terminate
The existing list and delete commands are updated and improved as well.
=> CB-1845 Begin expanding redbeams CLI support

dataplane/cmd/redbeams.go, dataplane/config/config.go, dataplane/flags/flags.go, dataplane/redbeams/redbeams.go
The following new commands are available for redbeams dbserver:
* create, for allocating new service-managed database servers
* register, for registering existing user-managed database servers
In addition:
The formerly separate describe / describe-by-name and get-status /
get-status-by-name redbeams operations are merged into single commands.
For either of the new commands, a valid call is one that passes either
only a CRN, or a pair of environment CRN and name. The command
implementations call the appropriate redbeams API endpoint depending
on the provided options.
New optional CRN flags are introduced, as well as a new function for
checking on valid "resource addressing" option combinations, in order
to enable this change.
=> CB-1845 Complete redbeams dbserver commands

dataplane/api-sdx/model/sdx_cluster_detail_response.go, dataplane/api-sdx/model/sdx_cluster_response.go, dataplane/sdx/sdx.go, dataplane/sdx/sdx_test.go
Response now looks like this:
```
{
"Crn": "crn:altus:sdx:us-west-1:default:sdxcluster:a680311f-0388-4556-9fd3-7bf53664277e",
"Name": "lnardai-repair-backup",
"environmentName": "lnardai-repair-test",
"environmentCrn": "crn:altus:environments:us-west-1:default:environment:55d53183-1c23-4765-8e2e-721eaaa057b5",
"stackCrn": "crn:altus:cloudbreak:us-west-1:default:stack:5b68c86e-3708-4433-9928-0a941dddbf40",
"databaseServerCrn": "crn:altus:redbeams:us-west-1:default:databaseServer:250af3ad-b731-492b-8e03-2d00489284c8",
"Status": "EXTERNAL_DATABASE_DELETION_IN_PROGRESS",
"StatusReason": ""
}
```
=> CB-2981 added databaseServerCrn to SDX response

dataplane/cmd/redbeams.go, dataplane/flags/flags.go, dataplane/redbeams/redbeams.go
The following new commands are available for redbeams db:
* list
* describe
* create, for creating new service-managed databases
* register, for registering existing user-managed databases
* delete, for deleting either service-managed or user-managed databases
=> CB-1857 Add redbeams db commands

dataplane/api-redbeams/client/database_servers/database_servers_client.go, dataplane/redbeams/redbeams.go
The redbeams database server client now requires authorization
information as an argument to calls, just as the database client already
has. This is needed because of the restoration of Swagger authorization
information in the redbeams database server API endpoint; generating
Swagger client code causes the appearance of the argument.
Because the CLI generally handles authorization itself through other
means, there is no need for any authorization information to be passed
to the generated client code, so everything just uses nil. It works.
=> CB-2909 Update redbeams dbserver client with authorization arg

dataplane/distrox/distrox.go
i want to search for specific cluster ids from crns but i need to check clusters one-by-one because no crn is printed in the response, so i have added that
=> Add Crn for distrox response

dataplane/audit/audit.go, dataplane/blueprint/blueprint.go, dataplane/clustertemplate/clustertemplate.go, dataplane/common/common.go, dataplane/connectors/connectors.go, dataplane/credential/credential.go, dataplane/distrox/distrox.go, dataplane/env/environment.go, dataplane/freeipa/freeipaoutlist.go, dataplane/freeipa/freeipaoutsyncoperation.go, dataplane/imagecatalog/imagecatalogs.go, dataplane/kerberos/kerberos.go, dataplane/kubernetes/kubernetes.go, dataplane/ldap/ldap.go, dataplane/mpack/mpack.go, dataplane/proxy/proxy.go, dataplane/rds/rds.go, dataplane/recipe/recipe.go, dataplane/redbeams/redbeams.go, dataplane/sdx/sdx.go, dataplane/stack/stack.go, dataplane/userprofile/userprofile.go, dataplane/workspace/workspace.go, tests/spec/integration/credential.rb
- all responses now start with lowercase so it's more similar to the API responses leading to less confusion better jq magic
- need to validate with QAAS if that's what they desire
```
API response:
{"crn":"crn:altus:sdx:us-west-1:9d74eee4-1cad-45d7-b645-7ccf9edbb73d:sdxcluster:975efde2-7d0e-4606-b327-b847381f551f","name":"zol-dl-z","clusterShape":"LIGHT_DUTY","status":"RUNNING","statusReason":null,"environmentName":"zol-sdx-z","environmentCrn":"crn:altus:environments:us-west-1:9d74eee4-1cad-45d7-b645-7ccf9edbb73d:environment:4d6402b5-5e07-407c-af8e-957978b26456","databaseServerCrn":null,"stackCrn":null,"created":null,"cloudStorageBaseLocation":null,"cloudStorageFileSystemType":null}
new CLI output:
{
"crn": "crn:altus:sdx:us-west-1:9d74eee4-1cad-45d7-b645-7ccf9edbb73d:sdxcluster:975efde2- …
```
=> CB-3069 uppercase slayer

dataplane/api-redbeams/model/database_v4_response.go, dataplane/redbeams/redbeams.go
The following changes are made to the redbeams commands:
* The database response object includes the new resource status field.
* The existing type field in the database response object is now
included in output.
* String conversions of ports and creation dates for table output are
fixed, and tabular output is generally fixed.
=> CB-3638 Add type and resource status to db output, fix int conversions

tests/requests/redbeams/create-redbeams-request.json, tests/requests/redbeams/register-redbeams-request.json, tests/responses/redbeams/create-redbeams-response.json, tests/responses/redbeams/dbs.json, tests/responses/redbeams/dbserver.json, tests/responses/redbeams/delete-redbeams-response.json, tests/responses/redbeams/register-redbeams-response.json, tests/responses/redbeams/release-redbeams-response.json, tests/scripts/aruba-docker.sh, tests/spec/common/mock_vars.rb, tests/spec/common/trace_response_builder.rb, tests/spec/integration/credential.rb, tests/spec/integration/redbeams.rb, tests/templates/dbserver-create-skeleton.json, tests/templates/dbserver-register-skeleton.json
This is the second part of our new REDBEAMS integration tests for PRs.
Now this contains all the visible DB Server commands in separate test cases.
In the next few days, based on my spare time, I'm going to write new test cases for visible DB commands.
=> CB-3087 Introduce new REDBEAMS integration test cases (part 2)

dataplane/redbeams/redbeams.go, tests/requests/redbeams/register-db-request.json, tests/spec/integration/redbeams.rb, tests/templates/db-register-skeleton.json
Logging of various redbeams commands no longer fails when a required
name field is nil in the request.
=> CB-3817 Fix logging of missing names for redbeams commands

dataplane/api-sdx/model/image_info_v4_response.go, dataplane/api/model/image_info_v4_response.go, dataplane/sdx/sdx.go
Contains the following:
- CB-6797 - ImageV4 response should return readable creation date
- Upgraded swagger image version to v0.19.0
=> CB-6797 - ImageV4 response should return readable creation date

dataplane/cmd/freeipa.go, dataplane/freeipa/freeipa.go, dataplane/freeipa/freeipaoutoperation.go
Add the FreeIPA repair command to the DP CLI.
This was tested by running it against a local deployment of
cloudbreak.
=> CB-7672: Add FreeIPA repair to DP CLI

tests/Makefile, tests/scripts/cbm.sh, tests/scripts/get-latest-version.sh, tests/scripts/mock-test-helper.sh
Our CB-CLI integration tests were not stable, because of:
```
CB_VERSION=2.27.0-b15 tmp/cbm.sh
curl -Ls s3.amazonaws.com/public-repo-1.hortonworks.com/HDP/cloudbreak/cloudbreak-deployer_2.27.0-b15_Linux_x86_64.tgz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
We have already implemented fallback for this. However that path is getting the `2.20.0-dev.126` instead of `2.27.0-b15`:
```
Getting the latest 'snapshot' version of CBD.
curl -Ls s3.amazonaws.com/public-repo-1.hortonworks.com/HDP/cloudbreak/cloudbreak-deployer_snapshot_Linux_x86_64.tgz
./cbd --version
echo 'CBD has been found with version: Cloudbreak Deployer: 2.20.0-dev.126-0930be3a'
CBD has been found with version: Cloudbreak Deployer: 2.20.0-dev.126-0930be3a
```
The …
=> CB-8044 Swagger version checker need to be updated for Int Tests

Makefile
* Fix `Makefile` target `install` to succeed in Linux deployments. Whereas Mac permits installing binaries to directory `/usr/local/bin` even for non-`root` users, Linux prohibits this. In order to avoid having to run the command as `root`, the compiled binary will be also copied to directory `~/.local/bin` that usually exists in Linux in the user home.
* `~/.local/bin` is not explicitly created. This is the user's responsibility, and so is adding that directory to `PATH`.
* Copy operations will be attempted for both locations, no matter which OS is being used. A failure of either copy will not make the target `install` fail.
* Add new `Makefile` target `dev-debug-linux` in analogy with `dev-debug-darwin`. Besides the different platform, this target will output the compiled binary to …
=> CB-14772 Fix Makefile for Linux
