hortonworks/cb-cli

README.md
=> Add binary install instruction

cli/flags.go, cli/imagecatalog_test.go, cli/imagecatalogs.go, cli/stack_template.go, cli/stack_template_test.go, main.go
=> CLOUD-93004 Register / deregister multiple catalogs from CLI

cli/cloud/yarn/stack_template.go
=> CLOUD-91579 put missing yanrQueue param during template generation

cli/flags.go, cli/ldap.go, main.go, models_cloudbreak/gateway_json.go, models_cloudbreak/ldap_config_request.go, models_cloudbreak/ldap_config_response.go
Depends on: https://github.com/hortonworks/cloudbreak/pull/2931
=> rename ldap admin group field

models_cloudbreak/kerberos_request.go
Depends on: https://github.com/hortonworks/cloudbreak/pull/2934
=> RMP-10239 Kerberos descriptor and krb5conf on API

cli/flags.go, cli/imagecatalog_test.go, cli/imagecatalogs.go, main.go
=> CLOUD-93172 [cb-cli] imagecatalog displays ami id instead of image uuid

cli/flags.go, cli/tags.go, cli/tags_test.go, main.go
=> CLOUD-93251 [cb-cli] Add support for managing default tags

cli/help.go, main.go
=> CLOUD-93244 CB CLI provides misleading cluster creation template

cli/blueprint.go, cli/cluster.go, cli/config.go, cli/connectors.go, cli/credential.go, cli/flags.go, cli/help.go, cli/imagecatalogs.go, cli/ldap.go, cli/recipe.go, cli/stack.go, cli/stack_template.go, cli/tags.go, main.go
=> CLOUD-93433 CLI skips certain fields

cli/cloud/azure/stack_template.go
=> CLOUD-94005 Support Azure Disk Encryption on CLI

cli/stack.go
=> CLOUD-93867 CB CLI does nothing when no name provided

Makefile, cli/cloud/aws/stack_template.go, cli/cloud/azure/stack_template.go, cli/cloud/cloud.go, cli/cloud/gcp/stack_template.go, cli/cloud/openstack/stack_template.go, cli/cloud/yarn/stack_template.go, cli/stack.go, cli/stack_template.go, cli/utils/utils.go, cli/utils/utils_test.go
=> CLOUD-94004 Support Azure availability sets on CLI

tests/scripts/e2e-test.sh
=> update parameter names

tests/e2e/blueprint.bats, tests/e2e/cluster.bats, tests/e2e/imagecatalog.bats, tests/e2e/template.bats, tests/integration/imagecatalog.bats, tests/resources.bash
=> CLOUD-94275 Extend E2E CLI tests

cli/oauth_client.go
=> CLOUD-94445 CB-CLI Create Cluster: Tag is missing from ERROR message

cli/utils/error_functions.go, tests/integration/cluster.bats
=> CLOUD-95591 [CLI] Too long error messages

cli/stack.go, cli/stack_template.go, main.go, models_cloudbreak/ambari_v2_request.go, models_cloudbreak/autoscale_stack_response.go, models_cloudbreak/cluster_request.go, models_cloudbreak/constraint_template_request.go, models_cloudbreak/constraint_template_response.go, models_cloudbreak/credential_request.go, models_cloudbreak/credential_response.go, models_cloudbreak/general_settings.go, models_cloudbreak/image_catalog_request.go, models_cloudbreak/image_catalog_response.go, models_cloudbreak/network_request.go, models_cloudbreak/placement_settings.go, models_cloudbreak/recipe_request.go, models_cloudbreak/recipe_response.go, models_cloudbreak/security_group_request.go, models_cloudbreak/stack_response.go, models_cloudbreak/stack_v2_request.go, models_cloudbreak/template_request.go, models_cloudbreak/topology_request.go, models_cloudbreak/topology_response.go, models_cloudbreak/update_image_catalog_request.go, tests/integration/blueprint.bats, tests/integration/cluster.bats
=> BUG-96588 [CLI] Eliminate NPEs during cluster create

cli/cloud/aws/stack_template.go, cli/cloud/azure/stack_template.go, cli/cloud/cloud.go, cli/cloud/gcp/stack_template.go, cli/cloud/openstack/stack_template.go, cli/cloud/yarn/stack_template.go, models_cloudbreak/stack_v2_request.go
=> BUG-96566 Cannot use CLI json skeleton generated by the UI

tests/e2e/blueprint.bats, tests/templates/aws-reinstall-template.json, tests/templates/aws-template.json, tests/templates/kilo-openstack-template.json, tests/templates/openstack-template.json, tests/templates/reinstall-template.json, tests/templates/template.json, tests/templates/template_wo_pwd.json
=> BUG-96685 Update Blueprint and Cluster  E2E tests

tests/e2e/imagecatalog.bats, tests/templates/kilo-openstack-template.json, tests/templates/openstack-template.json
=> BUG-96685 Update blueprint names in CLI tests

tests/e2e/blueprint.bats, tests/e2e/cluster.bats, tests/e2e/credential.bats, tests/templates/kilo-openstack-template.json, tests/utils/resources.bash
@mhalmy I've fixed the ruined methods and the cluster test cases as well TILL cluster scaling
=> BUG-94669 Fixes in support methods for wait-for-cluster-statuses

tests/templates/kilo-openstack-template.json, tests/templates/openstack-template.json
=> BUG-97823 Update cluster templates in CLI automated test project

main.go
=> BUG-98033 Implement Ldap command to cb cli, enable ldap commands

tests/integration/ldap.bats, tests/integration/rds.bats, tests/utils/commands.bash
=> BUG-98842 Extend Integration tests: RDS, LDAP

cli/flags.go, main.go
=> BUG-99038 [CLI] rename rds to rdbms in the cb cli

tests/integration/proxy.bats, tests/integration/rds.bats, tests/utils/commands.bash
=> BUG-99327 Add Proxy config cli mock test cases

tests/integration/imagecatalog.bats, tests/integration/rds.bats
Minor updates for the latest mock.
=> BUG-100624 Update Cloudbreak Mock with latest changes

cli/oauth_client.go, tests/Makefile, tests/docker-compose.yml, tests/scripts/cbm.sh
=> BUG-100755 cb cli does not work if server name contains a / at the end

tests/docker-compose.yml, tests/scripts/docker-integration-test.sh, tests/scripts/integration-test.sh
=> Fixing Mock Integration test environment issues

cli/flags.go, cli/stack_template.go, main.go
=> BUG-99813 Refactor Kerberos API, workaround for kerberos scenarios

cli/rds.go, models_cloudbreak/rds_config.go
https://github.com/hortonworks/cloudbreak/pull/3453 should be merged
=> oracleparameters -> oracle

tests/Makefile, tests/aruba/blueprints/test.bp, tests/aruba/scripts/recipe.sh, tests/aruba/scripts/test_run.sh, tests/aruba/spec/common/command_builder.rb, tests/aruba/spec/common/command_helpers.rb, tests/aruba/spec/common/e2e_vars.rb, tests/aruba/spec/common/helpers.rb, tests/aruba/spec/common/mock_vars.rb, tests/aruba/spec/e2e/blueprint.rb, tests/aruba/spec/e2e/cloud.rb, tests/aruba/spec/e2e/cluster.rb, tests/aruba/spec/e2e/credential.rb, tests/aruba/spec/e2e/image_catalog.rb, tests/aruba/spec/e2e/recipe.rb, tests/aruba/spec/e2e/spec_helper.rb, tests/aruba/spec/integration/blueprint.rb, tests/aruba/spec/integration/cloud.rb, tests/aruba/spec/integration/cluster.rb, tests/aruba/spec/integration/credential.rb, tests/aruba/spec/integration/image_catalog.rb, tests/aruba/spec/integration/recipe.rb, tests/aruba/spec/integration/spec_helper.rb, tests/aruba/templates/kilo-openstack-template.json, tests/aruba/templates/template-wo-pwd.json, tests/scripts/docker-integration-test-aruba.sh, tests/scripts/integration-test-aruba.sh
=> BUG-103089 re-write cli testcases with aruba-rspec

.circleci/config.yml, tests/Makefile, tests/aruba/spec/common/command_builder.rb, tests/aruba/spec/common/integration_formatter.rb, tests/aruba/spec/integration/blueprint.rb, tests/aruba/spec/integration/cluster.rb, tests/aruba/spec/integration/credential.rb, tests/aruba/spec/integration/image_catalog.rb, tests/aruba/spec/integration/recipe.rb, tests/aruba/templates/kilo-openstack-template.json, tests/scripts/docker-integration-test-aruba.sh, tests/scripts/integration-test-aruba.sh
=> BUG-102524 Configure CircleCI job for new cli integration tests

tests/aruba/spec/common/command_builder.rb, tests/aruba/spec/common/command_helpers.rb, tests/aruba/spec/common/helpers.rb, tests/aruba/spec/e2e/blueprint.rb, tests/aruba/spec/e2e/cloud.rb, tests/aruba/spec/e2e/cluster.rb, tests/aruba/spec/e2e/credential.rb, tests/aruba/spec/e2e/image_catalog.rb, tests/aruba/spec/e2e/recipe.rb, tests/aruba/spec/integration/blueprint.rb, tests/aruba/spec/integration/cloud.rb, tests/aruba/spec/integration/cluster.rb, tests/aruba/spec/integration/credential.rb, tests/aruba/spec/integration/image_catalog.rb, tests/aruba/tmp/aruba/placeholder
=> BUG-104479 improve teardown

tests/aruba/spec/e2e/cluster.rb
=> BUG-104479 Improve teardown in e2e CLI test cases

tests/aruba/spec/common/cluster_helpers.rb, tests/aruba/spec/common/command_builder.rb, tests/aruba/spec/common/command_helpers.rb, tests/aruba/spec/common/e2e_vars.rb, tests/aruba/spec/common/mock_vars.rb, tests/aruba/spec/e2e/blueprint.rb, tests/aruba/spec/e2e/cloud.rb, tests/aruba/spec/e2e/cluster.rb, tests/aruba/spec/e2e/credential.rb, tests/aruba/spec/e2e/database.rb, tests/aruba/spec/e2e/image_catalog.rb, tests/aruba/spec/e2e/ldap.rb, tests/aruba/spec/e2e/mpack.rb, tests/aruba/spec/e2e/proxy.rb, tests/aruba/spec/e2e/recipe.rb, tests/aruba/spec/integration/blueprint.rb, tests/aruba/spec/integration/cloud.rb, tests/aruba/spec/integration/cluster.rb, tests/aruba/spec/integration/credential.rb, tests/aruba/spec/integration/database.rb, tests/aruba/spec/integration/image_catalog.rb, tests/aruba/spec/integration/ldap.rb, tests/aruba/spec/integration/mpack.rb, tests/aruba/spec/integration/proxy.rb, tests/aruba/spec/integration/recipe.rb, tests/responses/mpacks/mpacks.json, tests/responses/responses.js, tests/scripts/docker-integration-test-aruba.sh
Please review it.
I ran successfully the new e2e test cases:
http://ci-cloudbreak.eng.hortonworks.com/view/e2e-test/job/cli-e2e-aruba/149/
=> BUG-104360 extend cli test cases

tests/aruba/spec/e2e/ldap.rb
=> BUG-106556

tests/Makefile, tests/scripts/cbm.sh
=> BUG-107783 Manage Docker IP automatically for Cloudbreak Mock

Makefile, tests/.gitignore, tests/Makefile, tests/aruba/README.md, tests/aruba/localvars, tests/aruba/spec/common/command_builder.rb, tests/aruba/spec/common/e2e_vars.rb, tests/aruba/spec/e2e/credential.rb, tests/aruba/spec/e2e/spec_helper.rb, tests/aruba/spec/integration/cluster.rb, tests/aruba/spec/integration/spec_helper.rb, tests/responses/responses.js, tests/responses/stacks/datalake.json, tests/scripts/cbm.sh, tests/scripts/docker-e2e-test-aruba-local.sh, tests/scripts/docker-integration-test-aruba.sh
=> BUG-106329 Improve test runner scripts

tests/Makefile, tests/scripts/docker-integration-test-aruba.sh, tests/scripts/jenkins-docker-e2e-test-aruba.sh
=> BUG-108033 Create Hortonworks Docker image - update scripts

tests/Dockerfile
=> BUG-108226 Add missing database tests - update Dockerfile

tests/aruba/spec/common/mock_vars.rb, tests/aruba/spec/common/response_helpers.rb, tests/aruba/spec/integration/database.rb, tests/aruba/spec/integration/spec_helper.rb
=> BUG-108226 Add missing database integration tests

tests/aruba/spec/integration/cluster.rb
=> BUG-108326 Update generate cluster template test

tests/aruba/spec/integration/cluster.rb, tests/responses/stacks/datalake.json
=> BUG-108326 Update Generate attached cluster template test - fix

tests/e2e/cluster.bats, tests/utils/resources.bash
@afarsang please review then merge if it is OK
=> BUG-108698 Improve 2.4 CB-CLI cluster create test case debug phase

.circleci/config.yml, tests/.gitignore, tests/Dockerfile, tests/aruba/README.md, tests/aruba/spec/common/mock_helper.rb, tests/aruba/spec/common/trace_response_builder.rb, tests/aruba/spec/e2e/spec_helper.rb, tests/aruba/spec/integration/org.rb, tests/aruba/spec/integration/spec_helper.rb, tests/aruba/spec/integration/user.rb, tests/requests/organizations/organizations.json, tests/responses/organizations/deleted-organization.json, tests/responses/organizations/organizations.json, tests/responses/users/users.json, tests/scripts/aruba-docker.sh, tests/scripts/docker-aruba-test.sh
@afarsang please review then merge if it is OK
FYI @mhalmy
=> BUG-108977 Create new CLI integration test cases for Organization

tests/aruba/spec/common/command_helpers.rb, tests/aruba/spec/common/mock_vars.rb, tests/aruba/spec/integration/audit.rb, tests/responses/audit/audit.json, tests/responses/audit/audit_single.json
=> BUG-108501 Add Audit integration tests

.circleci/config.yml, tests/.gitignore, tests/Dockerfile, tests/aruba/spec/e2e/spec_helper.rb, tests/aruba/spec/integration/spec_helper.rb, tests/scripts/aruba-docker.sh, tests/scripts/docker-aruba-test.sh
@mhalmy please review then merge
=> BUG-108251 New Alpine Aruba Docker image

tests/.gitignore, tests/Makefile, tests/aruba/spec/integration/org.rb, tests/aruba/spec/integration/user.rb, tests/scripts/cbm.sh, tests/scripts/docker-aruba-test.sh
=> BUG-109271 Introduce versioning, logging and cleanup for CB-CLI Mock

tests/aruba/spec/common/command_helpers.rb, tests/aruba/spec/e2e/audit.rb
Please, review it.
Test ran successfully on Jenkins:
http://ci-cloudbreak.eng.hortonworks.com/view/e2e-test/job/cli-e2e-aruba/325/RSpec_HTML_Report/
=> BUG-109253 Add audit e2e tests

tests/aruba/templates/kilo-openstack-template.json, tests/templates/kilo-openstack-template.json
=> BUG-109829 Remove volumes from os cluster templates

tests/aruba/spec/common/mock_vars.rb, tests/aruba/spec/integration/audit.rb, tests/aruba/spec/integration/cluster.rb, tests/aruba/spec/integration/database.rb, tests/aruba/spec/integration/spec_helper.rb, tests/responses/responses.js, tests/responses/stacks/datalake.json, tests/responses/stacks/openstack.json, tests/scripts/aruba-docker.sh
=> Update tests for org changes

cli/blueprint.go, cli/credential.go, cli/imagecatalogs.go, cli/ldap.go, cli/org.go, cli/rds.go, cli/recipe.go, cli/stack.go, main.go, tests/aruba/spec/integration/cluster.rb
=> BUG-109837 [CLI] Add ID field for describe command results

tests/aruba/spec/e2e/audit.rb
=> BUG-110138 Update e2e cli test cases for audit

cli/stack.go
=> BUG-110163 [CB CLI] Cluster describe gives back not enough info

tests/scripts/docker-aruba-test.sh
=> BUG-110354 Improve Aruba start script with advanced Docker image tagging

tests/aruba/spec/common/mock_helper.rb, tests/aruba/spec/integration/org.rb, tests/responses/responses.js
=> BUG-108977 Restore new CLI integration test cases for Organization

main.go
BUG-110398 – Hide reinstall functionality from cli
=> BUG-110398 – Hide reinstall functionality from cli

cli/blueprint.go, cli/recipe.go, tests/aruba/spec/e2e/blueprint.rb, tests/aruba/spec/integration/blueprint.rb
BUG-110153 – [CB CLI] cb recipe or blueprint describe does not list content
=> BUG-110153 – [CB CLI] cb recipe or blueprint describe does not list content

tests/aruba/spec/e2e/blueprint.rb
=> BUG-110501 Update Blueprint describe e2e cli test

cli/audit.go, cli/audit_test.go, cli/org.go, cli/org_test.go
BUG-110579 [CLI] audit describe, nil pointer result if the event is not a flow event
@keyki plz check
=> BUG-110577 [CLI] missing unit tests for audit and organization

cli/blueprint.go, cli/blueprint_test.go, tests/aruba/spec/integration/blueprint.rb
BUG-105237 – blueprint list and describe should have stack name and version instead of hdp version
=> BUG-105237 – blueprint list and describe should have stack name and version instead of hdp version

tests/aruba/spec/common/mock_helper.rb, tests/aruba/spec/common/response_helpers.rb, tests/aruba/spec/e2e/audit.rb, tests/aruba/spec/e2e/blueprint.rb, tests/aruba/spec/integration/audit.rb, tests/aruba/spec/integration/cluster.rb, tests/aruba/spec/integration/org.rb, tests/responses/responses.js
=> BUG-110582 Update cluster integration cli test cases

tests/scripts/aruba-docker.sh
@mhalmy Introduce trace information logging for CB binary CURL
=> Introduce trace information logging for CB CURL

tests/Dockerfile, tests/scripts/aruba-docker.sh
=> Curl CB-CLI cannot download entire TAR from S3

models_cloudbreak/ambari_v2_request.go, models_cloudbreak/cluster_request.go, models_cloudbreak/gateway_json.go
=> BUG-109191 Deeper ambari and stack repository check during cluster creation

tests/aruba/spec/common/mock_vars.rb, tests/aruba/spec/integration/environment.rb, tests/responses/environment/envs.json, tests/responses/environment/openstack.json, tests/responses/responses.js
=> BUG-112259 Add environment create, list test cases

tests/Dockerfile
=> BUG-114036 Update Dockerfile for aruba cli test image

tests/aruba/spec/integration/environment.rb, tests/responses/environment/envs.json, tests/responses/environment/openstack.json, tests/responses/responses.js
=> BUG-112259 Extend env test cases

tests/aruba/spec/common/e2e_vars.rb
=> BUG-114098 Cleanup CB CLI test folders - fix

tests/aruba/spec/common/e2e_vars.rb, tests/aruba/spec/common/mock_vars.rb
=> [CLI Test] BUG-114211 Update rawgit urls

Makefile, README.md, dataplane/config/config.go, tests/README.md, tests/scripts/aruba-docker.sh
Reverts hortonworks/cb-cli#387
=> Revert "RMP-12819 Rename CB CLI to DP CLI, rename s3 bucket and documentation"

dataplane/cmd/role.go, dataplane/cmd/user.go, dataplane/role/role.go, dataplane/user/user.go
BUG-113144 : Commands which got added are mentioned on https://hortonworks.jira.com/browse/RMP-12600
=> BUG-113144:Added commands related to user and role

tests/spec/e2e/proxy.rb
@mhalmy Please review! If it is OK for you, please merge.
@keyki and @attilapalfi92 it is FYI for you! The https://github.com/hortonworks/cb-cli/pull/370 PR has forgot about the E2E tests.
=> BUG-115637 Fix for Proxy 'json atom at path User is missing'

Makefile, cli/imagecatalogs.go, cli/recipe.go, client_cloudbreak/v1stacks/delete_instance_stack_parameters.go, client_cloudbreak/v2stacks/delete_instance_stack_v2_parameters.go, main.go, models_cloudbreak/instance_meta_data.go, models_cloudbreak/rds_test_result.go, models_cloudbreak/recipe_request.go, models_cloudbreak/recipe_response.go, tests/e2e/recipe.bats, tests/integration/recipe.bats, tests/utils/e2e_parameters.bash, tests/utils/mock_parameters.bash
Depends on: https://github.com/hortonworks/cloudbreak/pull/4266
=> BUG-115326 REmove recipe by url command

tests/e2e/imagecatalog.bats, tests/e2e/recipe.bats, tests/utils/e2e_parameters.bash
@lacikaaa please review and merge if it is OK for you!
FYI @gergopapi2  and @mhmxs
=> BUG-115326 Fixing Recipe and Image Catalog tests

tests/spec/common/e2e_vars.rb, tests/spec/common/mock_vars.rb, tests/templates/kilo-openstack-template.json, tests/templates/template-wo-pwd.json
=> BUG-116191 Use HDP 3.0 blueprints in CLI tests

tests/spec/common/command_builder.rb
=> BUG-117398 Fix command builder when using '_' char

cloudbreak/stack/stack_functions.go, cloudbreak/stack/stack_functions_test.go
=> CB-488 Forbidden response is not an error with delete --wait cmd

dataplane/api/model/cluster_v4_request.go, dataplane/api/model/stack_v4_request.go
CB-475 – Invalid Executor type: CONTAINER
=> CB-475 – Invalid Executor type: CONTAINER

tests/spec/common/e2e_vars.rb, tests/spec/e2e/cluster.rb, tests/spec/e2e/env.rb, tests/templates/kilo-openstack-template.json
@bbihari or @keyki please review and merge if it is OK for you.
=> CB-428 Update CLI E2E tests

cloudbreak/config/config.go
=> CB-705 new config parameter: httpRequestTimeout

dataplane/cmd/cluster.go, dataplane/stack/stack.go, dataplane/stack/stack_template.go, tests/responses/responses.js, tests/spec/e2e/cluster.rb, tests/spec/integration/cluster.rb
CB-677, CB-678 – remove reinstall and reinstall template and related tests
=> CB-677, CB-678 – remove reinstall and reinstall template and related tests

tests/recipes/echo.sh, tests/spec/common/e2e_vars.rb, tests/spec/e2e/blueprint.rb, tests/templates/kilo-openstack-template.json
@bbihari or @lnardai please review
=> Updates for E2E test cases based on latest changes

tests/spec/common/e2e_vars.rb
=> Fixed recipe types for E2E test cases

dataplane/api-sdx/client/sdx/create_sdx_parameters.go, dataplane/api-sdx/client/sdx/create_sdx_responses.go, dataplane/api-sdx/client/sdx/delete_sdx_parameters.go, dataplane/api-sdx/client/sdx/delete_sdx_responses.go, dataplane/api-sdx/client/sdx/get_sdx_parameters.go, dataplane/api-sdx/client/sdx/get_sdx_responses.go, dataplane/api-sdx/client/sdx/list_sdx_parameters.go, dataplane/api-sdx/client/sdx/list_sdx_responses.go, dataplane/api-sdx/client/sdx/redeploy_sdx_parameters.go, dataplane/api-sdx/client/sdx/redeploy_sdx_responses.go, dataplane/api-sdx/client/sdx/sdx_client.go, dataplane/api-sdx/model/sdx_cluster_request.go, dataplane/api-sdx/model/sdx_cluster_response.go, dataplane/cmd/sdx.go, dataplane/flags/flags.go, dataplane/sdx/sdx.go
- Updated API to the new version
- added describe endpoint for sdx
- tested all endpoints
=> CB-9 Updated CLI for latest SDX API

dataplane/cmd/environment.go, dataplane/env/environment.go
=> CB-1803 polish env creation

dataplane/sdx/sdx.go, dataplane/sdx/sdx_test.go
- environmentName and environmentCrn is present on the API
=> CB-1689 environment details on SdxResponse

dataplane/distrox/distrox.go
CB-2062 fix distrox describe empty json
=> CB-2062 fix distrox describe empty json

dataplane/env/environment.go
depends on https://github.com/hortonworks/cloudbreak/pull/5351
=> DISTX-197. Include telemetry in env responses

dataplane/sdx/sdx_test.go
This breaks the master pipeline.
=> CB-2230 statusreason breaks the unit test

dataplane/api/client/v4_workspace_id_stacks/get_cluster_hosts_inventory_responses.go, dataplane/api/client/v4_workspace_id_stacks/v4_workspace_id_stacks_client.go, dataplane/cmd/cluster.go, dataplane/flags/flags.go, dataplane/stack/stack.go
depends on https://github.com/hortonworks/cloudbreak/pull/5488
=> Add 'generate-inventory' command for cluster

dataplane/sdx/sdx.go, dataplane/sdx/sdx_test.go
depends on https://github.com/hortonworks/cloudbreak/pull/5649
now this can be merged
=> DISTX-258. Include stackCrn field on SDX side

dataplane/api-environment/model/detailed_environment_v1_response.go, dataplane/api-environment/model/environment_edit_v1_request.go, dataplane/api-environment/model/environment_v1_request.go, dataplane/api-environment/model/simple_environment_v1_response.go
CLI counterpart of https://github.com/hortonworks/cloudbreak/pull/5835.
=> CB-2863 Add IDBMMS to Env IdBrokerMappingSource

tests/spec/common/e2e_vars.rb, tests/spec/common/mock_vars.rb
@lnardai or @sodre90 please review then merge if it is Ok for you!
=> CB-2154 Update Image Catalog URL for tests

dataplane/api-sdx/client/sdx/repair_sdx_node_responses.go, dataplane/api-sdx/client/sdx/sdx_client.go, dataplane/api-sdx/model/sdx_cluster_detail_response.go, dataplane/api-sdx/model/sdx_cluster_response.go, dataplane/api-sdx/model/storage_location_base.go, dataplane/cmd/sdx.go, dataplane/flags/flags.go, dataplane/sdx/sdx.go, dataplane/sdx/sdx_test.go
- sdx cloud storage object only generate if there are correct values
- sdx createRds object is not default false
- regenerated the API
=> CB-3007 Sdx command fixed, 

dataplane/sdx/sdx.go, dataplane/sdx/sdx_test.go
needs work, QAAS requested to use the same notation as in our API responses
=> CB-3069 Capitalization fix for Sdx list view

dataplane/clustertemplate/clustertemplate.go, dataplane/cmd/clustertemplate.go
related to:
https://github.com/hortonworks/cloudbreak/pull/5979
=> CB-2874 - clustertemplate to commands (alias for blueprint)

dataplane/api-redbeams/model/database_v4_request.go, dataplane/api-redbeams/model/database_v4_response.go, dataplane/redbeams/redbeams.go
This is merely an update of generated code with one corresponding manual update.
=> CB-2687 Require env CRN in redbeams db requests

dataplane/audit/audit.go, dataplane/blueprint/blueprint.go, dataplane/clustertemplate/clustertemplate.go, dataplane/common/common.go, dataplane/connectors/connectors.go, dataplane/credential/credential.go, dataplane/distrox/distrox.go, dataplane/env/environment.go, dataplane/freeipa/freeipaoutlist.go, dataplane/freeipa/freeipaoutsyncoperation.go, dataplane/imagecatalog/imagecatalogs.go, dataplane/kerberos/kerberos.go, dataplane/kubernetes/kubernetes.go, dataplane/ldap/ldap.go, dataplane/mpack/mpack.go, dataplane/proxy/proxy.go, dataplane/rds/rds.go, dataplane/recipe/recipe.go, dataplane/redbeams/redbeams.go, dataplane/sdx/sdx.go, dataplane/stack/stack.go, dataplane/userprofile/userprofile.go, dataplane/workspace/workspace.go, tests/spec/integration/credential.rb
Reverts hortonworks/cb-cli#626
=> Revert "CB-3069 uppercase slayer"

dataplane/cmd/freeipa.go, dataplane/flags/flags.go, dataplane/freeipa/freeipa.go, dataplane/sdx/sdx.go
Both env-crn and env-name can be provided
=> simplify ipa sync for given environments

dataplane/api/model/blueprint_v4_response.go, dataplane/api/model/blueprint_v4_view_response.go, dataplane/api/model/cluster_template_v4_response.go, dataplane/api/model/cluster_template_view_v4_response.go, dataplane/api/model/recipe_v4_response.go, dataplane/api/model/recipe_view_v4_response.go, dataplane/blueprint/blueprint.go, dataplane/clustertemplate/clustertemplate.go, dataplane/recipe/recipe.go
blocks by https://github.com/hortonworks/cloudbreak/pull/6102
=> CB-2934 Add CreationDate to recipes, clusterDefinitions and Blueprint

dataplane/api/client/v4_workspace_id_blueprints/list_blueprints_by_workspace_parameters.go, dataplane/blueprint/blueprint.go, dataplane/blueprint/blueprint_test.go, dataplane/cmd/blueprint.go, dataplane/flags/flags.go
blocks by https://github.com/hortonworks/cloudbreak/pull/6148
=> CB-3349 Blueprint list needs a queryparameter to list sdx blueprints

dataplane/clusterdefinition/clusterdefinition.go, dataplane/cmd/clustertemplate.go
CB-3830 – make cluster definition operation(s) available
=> CB-3830 – make cluster definition operation(s) available

dataplane/cmd/sdx.go, dataplane/flags/flags.go, dataplane/sdx/sdx.go, dataplane/sdx/sdx_test.go
https://www.youtube.com/watch?v=7-iRf9AWoyE
=> CB-3804 multi hostgroup repair added for sdx

dataplane/cmd/sdx.go, dataplane/flags/flags.go, dataplane/flow/flow.go, dataplane/sdx/sdx.go
we have a details flag to include the stackV4Request for a datalake
`dp sdx describe --name datacatalog-190810-054545-t66-dd --details`
=> CB-4244 multi hostgroup repair added for sdx

dataplane/distrox/distrox.go
CB-4607 - distrox field content swap fix
=> CB-4607 - distrox field content swap fix

dataplane/distrox/distrox.go
CB-4608 - nodecount display for distrox
=> CB-4608 - nodecount display for distrox

dataplane/distrox/distrox.go
CB-4672 - fix duplicated field collision in struct for distrox
=> CB-4672 - fix duplicated field collision in struct for distrox

dataplane/config/config.go
=> CB-4061 Configurable httpRequestTimeout for the api calls

dataplane/api-environment/model/features_request.go, dataplane/api-environment/model/features_response.go
refresh telemetry feature request/response model
=> CB-5244. Rename clusterDeploymentLogsReport to clusterLogsCollection

tests/scripts/cbm.sh
=> CB-5525 RC 2.9 pull request integration test docker-compose init

dataplane/cmd/telemetry.go, dataplane/telemetry/telemetry.go
added new telemetry options for get/put account level telemetry
=> CB-6420. Add get/update account telemetry support

dataplane/api-environment/model/test_anonymization_rule_request.go, dataplane/cmd/telemetry.go, dataplane/telemetry/telemetry.go
+ updated object (for validation - use list of rules not only one)
=> CB-6647. Update test anonymization rule request object for validation

dataplane/api-sdx/model/sdx_upgrade_request.go, dataplane/cmd/sdx.go, dataplane/flags/flags.go, dataplane/sdx/sdx.go
This is the CLI implementation of the back-end effort tracked here: https://github.com/hortonworks/cloudbreak/pull/8673
=> CB-8119 - Introduce --show-available-images

tests/spec/common/e2e_vars.rb
CB-11107 Supporting paywall for existing HDP clusters
=> CB-11107 Supporting paywall for existing HDP clusters

dataplane/api-environment/model/detailed_environment_v1_response.go, dataplane/api-environment/model/environment_v1_request.go, dataplane/api-environment/model/simple_environment_v1_response.go, dataplane/api-freeipa/client/free_ip_a_client.go, dataplane/api-freeipa/client/v1freeipa/v1freeipa_client.go, dataplane/api-freeipa/model/create_free_ipa_v1_request.go, dataplane/api-freeipa/model/describe_free_ipa_v1_response.go, dataplane/api/client/autoscale/autoscale_client.go, dataplane/api/client/autoscale/get_recommendation1_parameters.go, dataplane/api/client/autoscale/get_recommendation1_responses.go, dataplane/api/client/autoscale/get_recommendation_parameters.go, dataplane/api/client/autoscale/get_recommendation_responses.go, dataplane/freeipa/freeipa.go
* Regenerate all the Swagger clients.
* Adapt `freeipa.go` in order to support the extra authentication arg.
=> CB-14663 Add TunnelType to FreeIPA response
